[package]
name = "flow-like-catalog"
version = "0.1.0"
edition = "2024"

[dependencies]
flow-like.workspace = true
flow-like-types.workspace = true
flow-like-model-provider.workspace = true
flow-like-storage.workspace = true
ahash.workspace = true
base64.workspace=true
fasteval = "0.2.4"
strsim = "0.11.1"
regex = "1.11.2"
chrono.workspace = true
calamine = { version = "0.30", default-features = false, features = ["dates"] }
umya-spreadsheet = "2.3.2"
nalgebra = "0.34.0"
schemars.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
csv-async = {version="1.3.0", features = ["tokio"]}
csv = "1.3"
htmd = "0.3.0"
scraper = "0.23.1"
async-imap = {version = "0.11.1", default-features = false, features = ["runtime-tokio", "tokio"]}
async-native-tls = { version = "0.5", default-features = false, features = ["runtime-tokio"] }
async-smtp = { version = "0.10.2", default-features = false, features = ["runtime-tokio", "tokio"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
mail-parser = "0.11.0"
tract-tflite = { git = "https://github.com/TM9657/tract", rev = "ed3b020" }
linfa = { git = "https://github.com/TM9657/linfa", rev = "071fb43", features = ["serde"]}
linfa-datasets = { git = "https://github.com/TM9657/linfa", rev = "071fb43", features = ["generate"]}
linfa-clustering = { git = "https://github.com/TM9657/linfa", rev = "071fb43", features = ["serde"]}
linfa-nn = { git = "https://github.com/TM9657/linfa", rev = "071fb43", features = ["serde"]}
linfa-linear = { git = "https://github.com/TM9657/linfa", rev = "071fb43", features = ["serde"]}
linfa-reduction = { git = "https://github.com/TM9657/linfa", rev = "071fb43", features = ["serde"]}
linfa-svm = { git = "https://github.com/TM9657/linfa", rev = "071fb43", features = ["serde"]}
ndarray.workspace = true
dirs-next.workspace = true
rayon = "1.11.0"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "flow_bench"
harness = false

[[bench]]
name = "throughput_bench"
harness = false

[profile.bench]
opt-level = 3
lto = "thin"
codegen-units = 1
debug = false
