[package]
name = "flow-like-catalog"
version = "0.1.0"
edition = "2024"

[dependencies]
flow-like.workspace = true
flow-like-types.workspace = true
flow-like-model-provider.workspace = true
flow-like-storage.workspace = true
fasteval = "0.2.4"
strsim = "0.11.1"
regex = "1.11.1"
chrono.workspace = true
nalgebra = "0.33.2"
schemars.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
rayon = "1.10.0"
csv = "1.3.1"
csv-async = {version="1.3.0", features = ["tokio"]}
htmd = "0.1.6"
scraper = "0.23.1"
