# .github/release.yml
changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - github-actions[bot]
      - dependabot[bot]

  categories:
    - title: "🚨 Breaking Changes"
      labels:
        - breaking
        - breaking-change
        - breaking changes

    - title: "✨ Features"
      labels:
        - feature
        - enhancement

    - title: "🐛 Fixes"
      labels:
        - fix
        - bug
        - bugfix

    - title: "🧰 Smaller Changes"
      labels:
        - task
        - chore
        - refactor
        - maintenance

    - title: "📦 Dependencies"
      labels:
        - dependencies

template: |
  ## 🚀 Flow-Like $RESOLVED_VERSION

  > Tagged: $TAG_NAME — Compare: $FULL_CHANGELOG

  ### What’s changed
  $CHANGES

  ### Contributors
  $CONTRIBUTORS
