[package]
name = "flow-like-api"
version = "0.1.0"
edition = "2024"

[build-dependencies]
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
flow-like-types.workspace = true
reqwest = { version = "0.12.15", features = ["blocking"] }

[dependencies]
axum.workspace = true
sea-orm.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
tower.workspace = true
flow-like.workspace = true
flow-like-types.workspace = true
flow-like-storage.workspace = true
serde_json.workspace = true
jsonwebtoken.workspace = true
hyper.workspace = true
hyper-util.workspace = true
tracing.workspace = true
tower-http.workspace = true
chrono.workspace = true
oasgen = {version="0.25.0", features = ["axum"]}
async-stripe.workspace = true
bitflags.workspace = true
futures-util.workspace = true
moka.workspace = true
blake3.workspace = true

# ---- AWS dependencies ----
aws-config = {version="1.6.3", optional=true}
aws-sdk-sts = {version="1.71.0", optional=true}
# -----

[features]
default = ["aws"]
aws = ["aws-config", "aws-sdk-sts"]
azure = []
gcp = []
local = []
full=[
    "aws",
    "azure",
    "gcp",
    "local",
]