[package]
name = "flow-like-api"
version = "0.1.0"
edition = "2024"

[build-dependencies]
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
flow-like-types.workspace = true
reqwest = { version = "0.12.15", features = ["blocking"] }

[dependencies]
axum.workspace = true
sea-orm.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
tower.workspace = true
tracing-subscriber.workspace = true
flow-like.workspace = true
flow-like-types.workspace = true
serde_json.workspace = true
dotenv.workspace = true
jsonwebtoken.workspace = true
hyper.workspace = true
hyper-util.workspace = true
tracing.workspace = true
sentry-tracing.workspace = true
sentry.workspace = true
sentry-tower.workspace = true
bytemuck.workspace = true
tower-http.workspace = true
chrono.workspace = true
oasgen = {version="0.25.0", features = ["axum"]}
async-stripe.workspace = true
bitflags = "2.9.1"
