[package]
name = "flow-like"
description = "Flow-Like, Automation done with the press of a Button. Core Library for Flow Execution and Management"
version = "0.1.0"
edition = "2024"
authors = ["TM9657 GmbH"]
repository = "https://github.com/TM9657/flow-like/"
categories = ["GenAI", "AI", "Productivity"]
license-file = "LICENSE"
readme = "README.md"

[lib]
name = "flow_like"
crate-type = ["lib", "cdylib", "staticlib"]
bench = false

[dependencies]
flow-like-types.workspace = true
flow-like-bits.workspace = true
flow-like-model-provider.workspace = true
flow-like-storage.workspace = true
rayon = "1.9.0"
portpicker = "0.1.1"
dirs-next = "2.0.0"
sysinfo = "0.33.0"
ignore = "0.4.23"
mime_guess = "2.0.5"
lopdf = "0.36.0"
pdf = "0.9.0"
id3 = "1.16.0"
mp4ameta = "0.12.1"
image = "0.25.5"
num_cpus = "1.16.0"
ahash = "0.8.11"
strsim = "0.11.1"
tempfile = "3.5.0"
lz4_flex = "0.11.3"
url = {version = "2.5.4", features = ["serde"]}
json5 = "0.4.1"
schemars.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
once_cell = "1.21.3"
tracing.workspace = true
highway = "1.3.0"
canonical_json = "0.5.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "flow_bench"
harness = false

[features]
tauri = ["flow-like-storage/tauri"]
schema-gen = []
flow-runtime = []
flow = ["flow-runtime"]
hub = []
bit = ["hub"]
model = ["bit"]
app = ["bit", "model", "hub"]
full = ["schema-gen", "flow-runtime", "flow", "hub", "bit", "model", "app"]
default = ["schema-gen", "flow-runtime", "flow", "hub", "bit", "model", "app"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "unwind"
strip = true
opt-level = "z"

[profile.dev]
opt-level = 1
