name: FOSSA License Scan

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FOSSA CLI
        run: |
          curl https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

      - name: Analyze with FOSSA
        run: fossa analyze --config .fossa.yml
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

      - name: Generate FOSSA report
        run: fossa report --config .fossa.yml --format html attribution
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

      - name: Upload FOSSA report artifact
        uses: actions/upload-artifact@v3
        with:
          name: fossa-report
          path: fossa.*